#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus

yabai -m config layout                       bsp

# new window spawns to the right if vertical, bottom if horizontal
yabai -m config window_placement             second_child

# floating windows are always on top
yabai -m config window_topmost               on
yabai -m config window_shadow                on

# render all unfocused windows with 90% opacity
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap


# gaps
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m config external_bar main:20:0


# float these apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add app="^1Password 7$" sticky=off manage=off

yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"spaces-widget\"'"

echo "yabai configuration loaded.."
