(use-package prog-mode
  :straight (:type built-in)
  :commands (prettify-symbols-mode global-prettify-symbols-mode)
  :init

  (setq prettify-symbols-unprettify-at-point 'right-edge)
  (create-hook-helper prettify-symbols-prog ()
    ""
    :hooks (prog-mode-hook)
    (push '(">=" . ?≥) prettify-symbols-alist)
    (push '("<=" . ?≤) prettify-symbols-alist)
    (push '("!=" . ?≠) prettify-symbols-alist)
    (push '("&&" . ?∧) prettify-symbols-alist)
    (push '("||" . ?∨) prettify-symbols-alist)
    (push '("lambda" . ?λ) prettify-symbols-alist)
    (push '("=>" . ?⇒) prettify-symbols-alist)
    (push '("->" . ?→) prettify-symbols-alist)
    (push '("[ERROR]" . #XE2C0) prettify-symbols-alist)
    (push '("[DEBUG]" . #XE2C1) prettify-symbols-alist)
    (push '("[INFO]" .  #XE2C2) prettify-symbols-alist)
    (push '("[WARN]" .  #XE2C3) prettify-symbols-alist)
    (push '("[WARNING]" . #XE2C4) prettify-symbols-alist)
    (push '("[ERR]" .     #XE2C5) prettify-symbols-alist)
    (push '("[FATAL]" .   #XE2C6) prettify-symbols-alist)
    (push '("[TRACE]" .   #XE2C7) prettify-symbols-alist)
    (push '("[FIXME]" .   #XE2C8) prettify-symbols-alist)
    (push '("[TODO]" .     #XE2C9) prettify-symbols-alist)
    (push '("[BUG]" .      #XE2CA) prettify-symbols-alist)
    (push '("[NOTE]" .     #XE2CB) prettify-symbols-alist)
    (push '("[HACK]" .     #XE2CC) prettify-symbols-alist)
    (push '("[MARK]" .     #XE2CD) prettify-symbols-alist)
    (push '("# ERROR" .    #XE2F0) prettify-symbols-alist)
    (push '("# DEBUG" .    #XE2F1) prettify-symbols-alist)
    (push '("# INFO" .     #XE2F2) prettify-symbols-alist)
    (push '("# WARN" .     #XE2F3) prettify-symbols-alist)
    (push '("# WARNING" .  #XE2F4) prettify-symbols-alist)
    (push '("# ERR" .      #XE2F5) prettify-symbols-alist)
    (push '("# FATAL" .    #XE2F6) prettify-symbols-alist)
    (push '("# TRACE" .    #XE2F7) prettify-symbols-alist)
    (push '("# FIXME" .    #XE2F8) prettify-symbols-alist)
    (push '("# TODO" .     #XE2F9) prettify-symbols-alist)
    (push '("# BUG" .      #XE2FA) prettify-symbols-alist)
    (push '("# NOTE" .     #XE2FB) prettify-symbols-alist)
    (push '("# HACK" .     #XE2FC) prettify-symbols-alist)
    (push '("# MARK" .     #XE2FD) prettify-symbols-alist)
    (push '("// ERROR" .   #XE2E0) prettify-symbols-alist)
    (push '("// DEBUG" .   #XE2E1) prettify-symbols-alist)
    (push '("// INFO" .    #XE2E2) prettify-symbols-alist)
    (push '("// WARN" .    #XE2E3) prettify-symbols-alist)
    (push '("// WARNING" . #XE2E4) prettify-symbols-alist)
    (push '("// ERR" .     #XE2E5) prettify-symbols-alist)
    (push '("// FATAL" .   #XE2E6) prettify-symbols-alist)
    (push '("// TRACE" .   #XE2E7) prettify-symbols-alist)
    (push '("// FIXME" .   #XE2E8) prettify-symbols-alist)
    (push '("// TODO" .    #XE2E9) prettify-symbols-alist)
    (push '("// BUG" .     #XE2EA) prettify-symbols-alist)
    (push '("// NOTE" .    #XE2EB) prettify-symbols-alist)
    (push '("// HACK" .    #XE2EC) prettify-symbols-alist)
    (push '("// MARK" .    #XE2ED) prettify-symbols-alist)
    (push '("!!" .         #XE900) prettify-symbols-alist)
    (push '("!=" .         #XE901) prettify-symbols-alist)
    (push '("!==" .        #XE902) prettify-symbols-alist)
    (push '("!!!" .        #XE903) prettify-symbols-alist)
    (push '("!≡" .         #XE904) prettify-symbols-alist)
    (push '("!≡≡" .        #XE905) prettify-symbols-alist)
    (push '("!>" .         #XE906) prettify-symbols-alist)
    (push '("!=<" .        #XE907) prettify-symbols-alist)
    (push '("#(" .         #XE920) prettify-symbols-alist)
    (push '("#_" .         #XE921) prettify-symbols-alist)
    (push '("#{" .         #XE922) prettify-symbols-alist)
    (push '("#?" .         #XE923) prettify-symbols-alist)
    (push '("#>" .         #XE924) prettify-symbols-alist)
    (push '("##" .         #XE925) prettify-symbols-alist)
    (push '("#_(" .        #XE926) prettify-symbols-alist)
    (push '("%=" .         #XE930) prettify-symbols-alist)
    (push '("%>" .         #XE931) prettify-symbols-alist)
    (push '("%>%" .        #XE932) prettify-symbols-alist)
    (push '("%<%" .        #XE933) prettify-symbols-alist)
    (push '("&%" .         #XE940) prettify-symbols-alist)
    (push '("&&" .         #XE941) prettify-symbols-alist)
    (push '("&*" .         #XE942) prettify-symbols-alist)
    (push '("&+" .         #XE943) prettify-symbols-alist)
    (push '("&-" .         #XE944) prettify-symbols-alist)
    (push '("&/" .         #XE945) prettify-symbols-alist)
    (push '("&=" .         #XE946) prettify-symbols-alist)
    (push '("&&&" .        #XE947) prettify-symbols-alist)
    (push '("&>" .         #XE948) prettify-symbols-alist)
    (push '("$>" .         #XE955) prettify-symbols-alist)
    (push '("***" .        #XE960) prettify-symbols-alist)
    (push '("*=" .         #XE961) prettify-symbols-alist)
    (push '("*/" .         #XE962) prettify-symbols-alist)
    (push '("*>" .         #XE963) prettify-symbols-alist)
    (push '("++" .         #XE970) prettify-symbols-alist)
    (push '("+++" .        #XE971) prettify-symbols-alist)
    (push '("+=" .         #XE972) prettify-symbols-alist)
    (push '("+>" .         #XE973) prettify-symbols-alist)
    (push '("++=" .        #XE974) prettify-symbols-alist)
    (push '("--" .         #XE980) prettify-symbols-alist)
    (push '("-<" .         #XE981) prettify-symbols-alist)
    (push '("-<<" .        #XE982) prettify-symbols-alist)
    (push '("-=" .         #XE983) prettify-symbols-alist)
    (push '("->" .         #XE984) prettify-symbols-alist)
    (push '("->>" .        #XE985) prettify-symbols-alist)
    (push '("---" .        #XE986) prettify-symbols-alist)
    (push '("-->" .        #XE987) prettify-symbols-alist)
    (push '("-+-" .        #XE988) prettify-symbols-alist)
    (push '("-\\/" .       #XE989) prettify-symbols-alist)
    (push '("-|>" .        #XE98A) prettify-symbols-alist)
    (push '("-<|" .        #XE98B) prettify-symbols-alist)
    (push '(".." .         #XE990) prettify-symbols-alist)
    (push '("..." .        #XE991) prettify-symbols-alist)
    (push '("..<" .        #XE992) prettify-symbols-alist)
    (push '(".>" .         #XE993) prettify-symbols-alist)
    (push '(".~" .         #XE994) prettify-symbols-alist)
    (push '(".=" .         #XE995) prettify-symbols-alist)
    (push '("/*" .         #XE9A0) prettify-symbols-alist)
    (push '("//" .         #XE9A1) prettify-symbols-alist)
    (push '("/>" .         #XE9A2) prettify-symbols-alist)
    (push '("/=" .         #XE9A3) prettify-symbols-alist)
    (push '("/==" .        #XE9A4) prettify-symbols-alist)
    (push '("///" .        #XE9A5) prettify-symbols-alist)
    (push '("/**" .        #XE9A6) prettify-symbols-alist)
    (push '(":::" .        #XE9AF) prettify-symbols-alist)
    (push '("::" .         #XE9B0) prettify-symbols-alist)
    (push '(":=" . #XE9B1) prettify-symbols-alist)
    (push '(":≡" .         #XE9B2) prettify-symbols-alist)
    (push '(":>" .         #XE9B3) prettify-symbols-alist)
    (push '(":=>" .        #XE9B4) prettify-symbols-alist)
    (push '(":(" .         #XE9B5) prettify-symbols-alist)
    (push '(":-(" .        #XE9B6) prettify-symbols-alist)
    (push '(":)" .         #XE9B7) prettify-symbols-alist)
    (push '(":-)" .        #XE9B8) prettify-symbols-alist)
    (push '(":/" .         #XE9B9) prettify-symbols-alist)
    (push '(":\\" .        #XE9BA) prettify-symbols-alist)
    (push '(":3" .         #XE9BB) prettify-symbols-alist)
    (push '(":D" .         #XE9BC) prettify-symbols-alist)
    (push '(":P" .         #XE9BD) prettify-symbols-alist)
    (push '(":>:" .        #XE9BE) prettify-symbols-alist)
    (push '(":<:" .        #XE9BF) prettify-symbols-alist)
    (push '("<$>" .        #XE9C0) prettify-symbols-alist)
    (push '("<*" .         #XE9C1) prettify-symbols-alist)
    (push '("<*>" .        #XE9C2) prettify-symbols-alist)
    (push '("<+>" .        #XE9C3) prettify-symbols-alist)
    (push '("<-" .         #XE9C4) prettify-symbols-alist)
    (push '("<<" .         #XE9C5) prettify-symbols-alist)
    (push '("<<<" .        #XE9C6) prettify-symbols-alist)
    (push '("<<=" .        #XE9C7) prettify-symbols-alist)
    (push '("<=" .         #XE9C8) prettify-symbols-alist)
    (push '("<=>" .        #XE9C9) prettify-symbols-alist)
    (push '("<>" .         #XE9CA) prettify-symbols-alist)
    (push '("<|>" .        #XE9CB) prettify-symbols-alist)
    (push '("<<-" .        #XE9CC) prettify-symbols-alist)
    (push '("<|" .         #XE9CD) prettify-symbols-alist)
    (push '("<=<" .        #XE9CE) prettify-symbols-alist)
    (push '("<~" .         #XE9CF) prettify-symbols-alist)
    (push '("<~~" .        #XE9D0) prettify-symbols-alist)
    (push '("<<~" .        #XE9D1) prettify-symbols-alist)
    (push '("<$" .         #XE9D2) prettify-symbols-alist)
    (push '("<+" .         #XE9D3) prettify-symbols-alist)
    (push '("<!>" .        #XE9D4) prettify-symbols-alist)
    (push '("<@>" .        #XE9D5) prettify-symbols-alist)
    (push '("<#>" .        #XE9D6) prettify-symbols-alist)
    (push '("<%>" .        #XE9D7) prettify-symbols-alist)
    (push '("<^>" .        #XE9D8) prettify-symbols-alist)
    (push '("<&>" .        #XE9D9) prettify-symbols-alist)
    (push '("<?>" .        #XE9DA) prettify-symbols-alist)
    (push '("<.>" .        #XE9DB) prettify-symbols-alist)
    (push '("</>" .        #XE9DC) prettify-symbols-alist)
    (push '("<\\>" .       #XE9DD) prettify-symbols-alist)
    (push '("<\" .>"       #XE9DE) prettify-symbols-alist)
    (push '("<:>" .        #XE9DF) prettify-symbols-alist)
    (push '("<~>" .        #XE9E0) prettify-symbols-alist)
    (push '("<**>" .       #XE9E1) prettify-symbols-alist)
    (push '("<<^" .        #XE9E2) prettify-symbols-alist)
    (push '("<!" .         #XE9E3) prettify-symbols-alist)
    (push '("<@" .         #XE9E4) prettify-symbols-alist)
    (push '("<#" .         #XE9E5) prettify-symbols-alist)
    (push '("<%" .         #XE9E6) prettify-symbols-alist)
    (push '("<^" .         #XE9E7) prettify-symbols-alist)
    (push '("<&" .         #XE9E8) prettify-symbols-alist)
    (push '("<?" .         #XE9E9) prettify-symbols-alist)
    (push '("<." .         #XE9EA) prettify-symbols-alist)
    (push '("</" .         #XE9EB) prettify-symbols-alist)
    (push '("<\\" .        #XE9EC) prettify-symbols-alist)
    (push '("<\" ."        #XE9ED) prettify-symbols-alist)
    (push '("<:" .         #XE9EE) prettify-symbols-alist)
    (push '("<->" .        #XE9EF) prettify-symbols-alist)
    (push '("<!--" .       #XE9F0) prettify-symbols-alist)
    (push '("<--" .        #XE9F1) prettify-symbols-alist)
    (push '("<~<" .        #XE9F2) prettify-symbols-alist)
    (push '("<==>" .       #XE9F3) prettify-symbols-alist)
    (push '("<|-" .        #XE9F4) prettify-symbols-alist)
    (push '("<<|" .        #XE9F5) prettify-symbols-alist)
    (push '("<-<" .        #XE9F7) prettify-symbols-alist)
    (push '("<-->" .       #XE9F8) prettify-symbols-alist)
    (push '("<<==" .       #XE9F9) prettify-symbols-alist)
    (push '("<==" .        #XE9FA) prettify-symbols-alist)
    (push '("=<<" .        #XEA00) prettify-symbols-alist)
    (push '("==" .         #XEA01) prettify-symbols-alist)
    (push '("===" .        #XEA02) prettify-symbols-alist)
    (push '("==>" .        #XEA03) prettify-symbols-alist)
    (push '("=>" .         #XEA04) prettify-symbols-alist)
    (push '("=~" .         #XEA05) prettify-symbols-alist)
    (push '("=>>" .        #XEA06) prettify-symbols-alist)
    (push '("=/=" .        #XEA07) prettify-symbols-alist)
    (push '("=~=" .        #XEA08) prettify-symbols-alist)
    (push '("==>>" .       #XEA09) prettify-symbols-alist)
    (push '("≡≡" .         #XEA10) prettify-symbols-alist)
    (push '("≡≡≡" .        #XEA11) prettify-symbols-alist)
    (push '("≡:≡" .        #XEA12) prettify-symbols-alist)
    (push '(">-" .         #XEA20) prettify-symbols-alist)
    (push '(">=" .         #XEA21) prettify-symbols-alist)
    (push '(">>" .         #XEA22) prettify-symbols-alist)
    (push '(">>-" .        #XEA23) prettify-symbols-alist)
    (push '(">>=" .        #XEA24) prettify-symbols-alist)
    (push '(">>>" .        #XEA25) prettify-symbols-alist)
    (push '(">=>" .        #XEA26) prettify-symbols-alist)
    (push '(">>^" .        #XEA27) prettify-symbols-alist)
    (push '(">>|" .        #XEA28) prettify-symbols-alist)
    (push '(">!=" .        #XEA29) prettify-symbols-alist)
    (push '(">->" .        #XEA2A) prettify-symbols-alist)
    (push '("??" .         #XEA40) prettify-symbols-alist)
    (push '("?~" .         #XEA41) prettify-symbols-alist)
    (push '("?=" .         #XEA42) prettify-symbols-alist)
    (push '("?>" .         #XEA43) prettify-symbols-alist)
    (push '("???" .        #XEA44) prettify-symbols-alist)
    (push '("?." .         #XEA45) prettify-symbols-alist)
    (push '("^=" .         #XEA48) prettify-symbols-alist)
    (push '("^." .         #XEA49) prettify-symbols-alist)
    (push '("^?" .         #XEA4A) prettify-symbols-alist)
    (push '("^.." .        #XEA4B) prettify-symbols-alist)
    (push '("^<<" .        #XEA4C) prettify-symbols-alist)
    (push '("^>>" .        #XEA4D) prettify-symbols-alist)
    (push '("^>" .         #XEA4E) prettify-symbols-alist)
    (push '("\\\\" .       #XEA50) prettify-symbols-alist)
    (push '("\\>" .        #XEA51) prettify-symbols-alist)
    (push '("\\/-" .       #XEA52) prettify-symbols-alist)
    (push '("@>" .         #XEA57) prettify-symbols-alist)
    (push '("|=" .         #XEA60) prettify-symbols-alist)
    (push '("||" .         #XEA61) prettify-symbols-alist)
    (push '("|>" .         #XEA62) prettify-symbols-alist)
    (push '("|||" .        #XEA63) prettify-symbols-alist)
    (push '("|+|" .        #XEA64) prettify-symbols-alist)
    (push '("|->" .        #XEA65) prettify-symbols-alist)
    (push '("|-->" .       #XEA66) prettify-symbols-alist)
    (push '("|=>" .        #XEA67) prettify-symbols-alist)
    (push '("|==>" .       #XEA68) prettify-symbols-alist)
    (push '("|>-" .        #XEA69) prettify-symbols-alist)
    (push '("|<<" .        #XEA6A) prettify-symbols-alist)
    (push '("||>" .        #XEA6B) prettify-symbols-alist)
    (push '("|>>" .        #XEA6C) prettify-symbols-alist)
    (push '("|-" .         #XEA6D) prettify-symbols-alist)
    (push '("||-" .        #XEA6E) prettify-symbols-alist)
    (push '("~=" .         #XEA70) prettify-symbols-alist)
    (push '("~>" .         #XEA71) prettify-symbols-alist)
    (push '("~~>" .        #XEA72) prettify-symbols-alist)
    (push '("~>>" .        #XEA73) prettify-symbols-alist)
    (push '("[[" .         #XEA80) prettify-symbols-alist)
    (push '("]]" .         #XEA81) prettify-symbols-alist)
    (push '("\" .>"        #XEA90) prettify-symbols-alist)
    (push '("_|_" .        #XEA97) prettify-symbols-alist)
    (push '("nil" . ?∅) prettify-symbols-alist))
  (create-hook-helper prettify-symbols-lisp ()
    ""
    :hooks' (lisp-mode-hook)
    (push ''("/=" . ?≠) prettify-symbols-alist)
    (push '("sqrt" . ?√) prettify-symbols-alist)
    (push '("not" . ?¬) prettify-symbols-alist)
    (push '("and" . ?∧) prettify-symbols-alist)
    (push '("or" . ?∨) prettify-symbols-alist))
  (create-hook-helper prettify-symbols-js ()
    ""
    :hooks (js2-mode-hook rjsx-mode-hook js-mode-hook typescript-mode-hook typescript-tsx-mode-hook)
    (push '("function()" . ?λ) prettify-symbols-alist)
    (push '(" () " . ?λ) prettify-symbols-alist)
    (push '("null" . ?∅) prettify-symbols-alist))
  (create-hook-helper prettify-symbols-python ()
    ""
    :hooks (python-mode-hook)
    (push '("and" . ?∧) prettify-symbols-alist)
    (push '("or" . ?∨) prettify-symbols-alist))
  (global-prettify-symbols-mode))

(use-package hideshow
  :straight (:type built-in))
;; :hook (prog-mode . hs-minor-mode)
;; :bind (:map hs-minor-mode-map
;;         ("C-`" . hs-toggle-hiding)))

(use-package protobuf-mode)

(use-package yaml-mode)

(use-package terraform-mode)

(use-package csv-mode)

(use-package cask-mode)

(use-package lua-mode)

(use-package vimrc-mode)

(use-package plantuml-mode
  :mode "\\.puml\\'"
  :config
  (setq homebrew-plantuml-jar-path
    (expand-file-name
      (string-trim (shell-command-to-string "brew list plantuml | grep jar"))))
  :custom
  (plantuml-jar-path homebrew-plantuml-jar-path)
  (plantuml-default-exec-mode 'executable))

(use-package graphviz-dot-mode
  :commands graphviz-dot-mode
  :mode ("\\.dot'" . graphviz-dot-mode))

(use-package ssh-config-mode)

(use-package vyper-mode)

(use-package conf-mode
  :straight (:type built-in)
  :mode (rx (or ".list"
              "CODEOWNERS"
              (and ".env" (* (and "." (+ word))))
              (and "." (+ word) "rc"))
          eos))

(use-package mermaid-mode
  :mode (("\\.mermaid\\'" . mermaid-mode)))

(advice-add 'risky-local-variable-p :override #'ignore)

(provide 'init-prog)
;;; init-prog.el ends here
