setopt no_global_rcs

# home
if [[ "$OSTYPE" == "darwin"* ]]; then
  export HOME="/Users/$(whoami)"
fi

# XDG_CONFIG_HOME
export XDG_CONFIG_HOME=$HOME/.config


if [[ "$OSTYPE" == "darwin"* ]]; then
  source "$HOME/Code/dot/zsh/zshenv.mac"
else
  source "$HOME/Code/dot/zsh/zshenv.linux"
fi

export LSP_USE_PLISTS=true


# local config
[[ -f "$HOME/Code/dot/zsh/zshenv.local" ]] && source "$HOME/Code/dot/zsh/zshenv.local"
